version: '3'

services:

  data_base:
    image: 'mysql:8'
    container_name: mysql_credentials
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DDBB_PASSWORD}
      TZ: America/Santiago
    volumes:
      - './credentials:/var/lib/docker/volumes/crentials'
    networks:
      net_interna:
        aliases:
          - api_net_credentials
  
  backend:
    image: api_credenciales:latest
    container_name: spring_boot
    build:
      context: ../Backend/
      dockerfile: Dockerfile
    depends_on:
      - data_base      
    networks:
      net_interna:
        aliases:
          - api_net_backend

volumes:
  credenciales: {}

networks:
  net_interna:
    name: api_net
    driver: bridge
    ipam:
      driver: default
