version: '3'

services:

  data_base:
    image: 'mysql:8'
    container_name: mysql_credentials
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - ${DDBB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DDBB_PASSWORD}
      TZ: America/Santiago
    volumes:
      - './credentials:/var/lib/docker/volumes/crentials'
    networks:
      net_interna:
        aliases:
          - api_net_credentials_database

  sftp:
    image: atmoz/sftp
    container_name: sftp_credentials
    platform: linux/x86_64
    volumes:
        - ${SFTP_DIR}/upload:/home/foo/upload
    ports:
        - ${SFTP_PORT}
    command: foo:pass:1001
    networks:
      net_interna:
        aliases:
          - api_net_credentials_sftp

volumes:
  credenciales: {}

networks:
  net_interna:
    name: api_net_credentials
    driver: bridge
    ipam:
      driver: default
