server:
  port: 8081

logging:
  level:
    org: 
      springframework:
        security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/CREDENTIALS
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        "[default_schema]": CREDENTIALS
        hbm2ddl:
          auto: none
          
